# Config format schema number
format_version: 1

###################
## Dataset options
dataset_params:
  dataset_type: "point_image_dataset_semkitti"
  pc_dataset_type: "SemanticKITTI"
  collate_type: "collate_fn_default"
  num_classes: 20
  ignore_label: 0
  label_mapping: "/userHome/xzy/Projects/elon/TransLiDAR/config/label_mapping.yaml"


  data_loader:
    data_path: "/data/xzy/elon/TransLiDAR_bin/sequences/"
    shuffle: False
    num_workers: 1
    batch_size: 1
    



colorMap: 
  - [0, 0, 0]          # 0 "unlabeled"
  - [100, 150, 245]    # 1 "car"
  - [100, 230, 245]    # 2 "bicycle"
  - [30, 60, 150]      # 3 "motorcycle"
  - [80, 30, 180]      # 4 "truck"
  - [100, 80, 250]     # 5 "other-vehicle"
  - [255, 30, 30]      # 6 "person"
  - [255, 40, 200]     # 7 "bicyclist"
  - [150, 30, 90]      # 8 "motorcyclist"
  - [255, 0, 255]      # 9 "road"
  - [255, 150, 255]    # 10 "parking"
  - [75, 0, 75]        # 11 "sidewalk"
  - [175, 0, 75]       # 12 "other-ground"
  - [255, 200, 0]      # 13 "building"
  - [255, 120, 50]     # 14 "fence"
  - [0, 175, 0]        # 15 "vegetation"
  - [135, 60, 0]       # 16 "trunk"
  - [150, 240, 80]     # 17 "terrain"
  - [255, 240, 150]    # 18 "pole"
  - [255, 0, 0]        # 19 "traffic-sign"


# colorMap: 
#   - [128, 128, 128]          # 0 "unlabeled"
#   - [128, 128, 128]    # 1 "car"
#   - [255, 0, 0]     # 2 "bicycle"
#   - [128, 128, 128]      # 3 "motorcycle"
#   - [128, 128, 128]      # 4 "truck"
#   - [128, 128, 128]     # 5 "other-vehicle"
#   - [128, 128, 128]      # 6 "person"
#   - [128, 128, 128]     # 7 "bicyclist"
#   - [128, 128, 128]      # 8 "motorcyclist"
#   - [255, 0, 255]      # 9 "road"
#   - [128, 128, 128]    # 10 "parking"
#   - [128, 128, 128]        # 11 "sidewalk"
#   - [128, 128, 128]       # 12 "other-ground"
#   - [128, 128, 128]      # 13 "building"
#   - [128, 128, 128]     # 14 "fence"
#   - [128, 128, 128]        # 15 "vegetation"
#   - [128, 128, 128]       # 16 "trunk"
#   - [128, 128, 128]     # 17 "terrain"
#   - [128, 128, 128]    # 18 "pole"
#   - [128, 128, 128]        # 19 "traffic-sign"

